### PR TITLE
Updated dependencies i os7+

### PR DESCRIPTION
**Pull request by danwalkowski**
I rolled back a change that was leaking a CFRef, which is just s few bytes, due to a tricky race condition.
I know now why the original author didn't fix it.

### CODE REVIEW

**Comment by shortstuffsushi** [comment]
... As the original author of this, I'm not sure what adding this originally fixed, or what removing here fixes. Could you explain? Does #35 have any info?

**Comment by shortstuffsushi** [comment]
I thought I had left comments on that PR, but they seem to be gone (perhaps deleted?), but could you explain both that and this reversal?

**Comment by shortstuffsushi** [comment]
Oh, wrong PR by the looks of it. My comments were on #33.

So, in addition to my above questions, could you explain the difference between #33, #34, #35, and this? They all appear to be variations of the same code (and maybe branch?) and I can't seem to figure out why.

**Comment by danwalkowski** [comment]
Please see my comment on #33

**Pull request merged**
