### PR TITLE
Change import statement

### PR DESCRIPTION
**Pull request by rishabhtayal**
The import statement were causing error in swift frameworks in cocoa
pods project.

### CODE REVIEW

**Comment by shortstuffsushi** [comment]
Were you able to confirm that this fixes the framework issues you were seeing in #29?

**Comment by rishabhtayal** [comment]
@shortstuffsushi Yes.

**Comment by shortstuffsushi** [comment]
I believe this needs to be added in the [Share Category](https://github.com/BranchMetrics/Branch-iOS-Invite-SDK/blob/5fbeeeff058fd92cf3cac1a401c4b9cb8339a952/Classes/Sharing/UIViewController%2BBranchShare.m#L10) as well, right?

**Comment by shortstuffsushi** [comment]
And the [Referral Controller](https://github.com/BranchMetrics/Branch-iOS-Invite-SDK/blob/5fbeeeff058fd92cf3cac1a401c4b9cb8339a952/Classes/Referral/BranchReferralController.m#L12) as well.

**Comment by francisjervis** [comment]
https://github.com/CocoaPods/CocoaPods/issues/3105 <https://github.com/CocoaPods/CocoaPods/issues/3105>
https://github.com/CocoaPods/CocoaPods/issues/3267 <https://github.com/CocoaPods/CocoaPods/issues/3267>
https://github.com/CocoaPods/CocoaPods/issues/2926 <https://github.com/CocoaPods/CocoaPods/issues/2926>

@ShortStuffSushi is Branch a vendored framework? Static library? Might be a fix around linking HMSegmentedControl to the right target...

**Comment by shortstuffsushi** [comment]
@francisjervis, I don't think so, but I'm not entirely sure what a "vendored framework" is in this case. We don't provide static files, just the source, which is compiled as a part of the Pods target, so I think we wouldn't fall into that category (that seems to be the case for people who provide, for instance, only Public Headers and a .framework file to Cocoapods, like Google or FBSDK).

**Comment by shortstuffsushi** [comment]
Notice as well that we aren't being explicitly rejected as a part of the Pods build process, so I don't think that's the issue.

**Comment by rishabhtayal** [comment]
@shortstuffsushi I am not getting any error after updating the import statements but I can definitely change the suggested ones as well. Please advice.

**Comment by shortstuffsushi** [comment]
@rishabhtayal I think it would be best to be consistent, I'd go for `<Branch/Branch.h>` throughout :+1:

**Comment by rishabhtayal** [comment]
@shortstuffsushi Done

**Comment by shortstuffsushi** [comment]
Looks great to me! Thanks @rishabhtayal :smile:

**Comment by rishabhtayal** [comment]
:+1:

**Comment by rishabhtayal** [comment]
@shortstuffsushi Do I need to wait for new release?

**Comment by shortstuffsushi** [comment]
I am in the process right now, will be available on Cocoapods shortly.

**Comment by shortstuffsushi** [comment]
Alright, done now, let me know if you see any additional issues. Thanks again!

**Pull request merged**
